
#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper
exec-once = systemctl --user start hyprpolkitagent
exec-once = elephant & walker --gapplication-service
exec-once = tuxedo-control-center --tray # remove if not on a tuxedo obviously
